package com._864zeros.clearstreak.database

import com._864zeros.clearstreak.model.CopingCard
import com._864zeros.clearstreak.model.UrgeLevel

object CopingCardsSeed {

    val SEED_CARDS = listOf(
        // === HUNGRY ===
        CopingCard(
            id = "c_h_01",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Drink 16oz of cold water and eat a protein-rich snack like almonds, cheese, or peanut butter.",
            rationale = "Low blood sugar mimics physical anxiety and dopamine cravings. Fueling your body stabilizes nervous system triggers."
        ),
        CopingCard(
            id = "c_h_02",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Prepare a warm cup of herbal tea and focus solely on the sensation of warmth in your hands.",
            rationale = "Warm liquids trigger the parasympathetic rest-and-digest response, reducing physiological tension."
        ),
        CopingCard(
            id = "c_h_03",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Eat something with intense flavor—a slice of lemon, a pickle, or a mint. Chew slowly for 60 seconds.",
            rationale = "Strong gustatory sensations shock the sensory cortex and interrupt obsessive behavioral feedback loops."
        ),
        CopingCard(
            id = "c_h_04",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Eat a balanced solid meal. Step away from all screens while you eat.",
            rationale = "Mindful eating engages the enteric nervous system and halts fight-or-flight panic driven by hypoglycemia."
        ),
        CopingCard(
            id = "c_h_05",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Put an ice cube in your mouth. Let it melt completely without biting it while drinking a glass of cold water.",
            rationale = "Somatic temperature disruption forces immediate nervous system regulation through the mammalian dive reflex."
        ),
        CopingCard(
            id = "c_h_06",
            triggerCategory = "HUNGRY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Check when you last ate. If it's been more than 4 hours, eat a small complex carbohydrate snack.",
            rationale = "Predictable nourishment restores prefrontal cortex glucose, which is required for executive impulse control."
        ),

        // === ANGRY ===
        CopingCard(
            id = "c_a_01",
            triggerCategory = "ANGRY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Do 20 vigorous jumping jacks or pushups against a wall to release adrenaline.",
            rationale = "Physical exertion metabolizes excess cortisol and epinephrine generated by anger."
        ),
        CopingCard(
            id = "c_a_02",
            triggerCategory = "ANGRY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Grab a piece of scrap paper and write down everything you are furious about. Then tear it into tiny shreds.",
            rationale = "Externalizing rage kinesthetically provides symbolic catharsis without destructive real-world fallout."
        ),
        CopingCard(
            id = "c_a_03",
            triggerCategory = "ANGRY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Clench both fists as tightly as possible for 10 seconds, then completely release. Repeat 3 times.",
            rationale = "Progressive muscle relaxation releases neuromuscular tension held during emotional flare-ups."
        ),
        CopingCard(
            id = "c_a_04",
            triggerCategory = "ANGRY",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Step outside immediately. Walk at a brisk pace for 10 minutes without looking at your phone.",
            rationale = "Changing your physical geography removes immediate anger stimuli and engages bilateral brain stimulation."
        ),
        CopingCard(
            id = "c_a_05",
            triggerCategory = "ANGRY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Say out loud: 'I can feel angry without making a decision right now.'",
            rationale = "Cognitive separation decouples the intense emotion of anger from reactive self-destructive impulses."
        ),

        // === LONELY ===
        CopingCard(
            id = "c_l_01",
            triggerCategory = "LONELY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Send a simple check-in text to a friend, sponsor, or family member: 'Thinking of you, hope you're having a good day.'",
            rationale = "Outward-focused connection shifts the brain out of self-isolation and activates social safety circuits."
        ),
        CopingCard(
            id = "c_l_02",
            triggerCategory = "LONELY",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Go to a public space—a coffee shop, library, or park. Sit among people for 15 minutes.",
            rationale = "Passive social presence provides comforting ambient human connection without social performance pressure."
        ),
        CopingCard(
            id = "c_l_03",
            triggerCategory = "LONELY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Call your sponsor or a recovery support line right now. You do not have to know what to say.",
            rationale = "Vocal interaction activates the ventral vagal complex, rapidly reducing feelings of acute isolation."
        ),
        CopingCard(
            id = "c_l_04",
            triggerCategory = "LONELY",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Write a letter of gratitude to someone who has helped you in your life. You don't have to send it.",
            rationale = "Gratitude recall floods neural pathways with oxytocin and counters feelings of perceived abandonment."
        ),
        CopingCard(
            id = "c_l_05",
            triggerCategory = "LONELY",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Open a virtual or local recovery meeting finder and join an open session immediately.",
            rationale = "Immersing in a recovery community replaces isolation with shared purpose and mutual safety."
        ),

        // === TIRED ===
        CopingCard(
            id = "c_t_01",
            triggerCategory = "TIRED",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Splash cold water on your face, wrists, and the back of your neck.",
            rationale = "Cold cutaneous stimulation activates sympathetic alertness and increases cerebral blood flow."
        ),
        CopingCard(
            id = "c_t_02",
            triggerCategory = "TIRED",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Lie down, close your eyes, and set a timer for a 20-minute power nap or non-sleep deep rest (NSDR).",
            rationale = "Exhaustion erodes prefrontal willpower; a brief neurological reset restores impulse control capacity."
        ),
        CopingCard(
            id = "c_t_03",
            triggerCategory = "TIRED",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Turn down the lights, put your phone away, and prepare your bed for sleep.",
            rationale = "Many urges are simply fatigue in disguise. The urge will pass once your body receives restorative rest."
        ),
        CopingCard(
            id = "c_t_04",
            triggerCategory = "TIRED",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Step into direct natural sunlight for 5 minutes and take 10 deep breaths.",
            rationale = "Natural photons on retinal ganglion cells trigger circadian wakefulness and dopamine baseline reset."
        ),

        // === STRESSED ===
        CopingCard(
            id = "c_s_01",
            triggerCategory = "STRESSED",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Look around you and name 5 things you see, 4 you feel, 3 you hear, 2 you smell, and 1 good thing about yourself.",
            rationale = "The 5-4-3-2-1 somatic grounding method anchors awareness in the present moment, halting panic spirals."
        ),
        CopingCard(
            id = "c_s_02",
            triggerCategory = "STRESSED",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Complete 4 rounds of box breathing: Inhale 4s, Hold 4s, Exhale 4s, Hold 4s.",
            rationale = "Equalized respiratory rhythm down-regulates amygdala hyperactivity and lowers heart rate variability stress."
        ),
        CopingCard(
            id = "c_s_03",
            triggerCategory = "STRESSED",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Take a hot shower or wash your hands in warm water with pleasant scented soap.",
            rationale = "Thermal sensory comfort stimulates oxytocin release and eases chronic muscle tension."
        ),
        CopingCard(
            id = "c_s_04",
            triggerCategory = "STRESSED",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Drop your shoulders away from your ears, unclench your jaw, and uncurl your toes. Breathe out completely.",
            rationale = "Conscious release of physical guarding signals safety to the primitive survival brain."
        ),
        CopingCard(
            id = "c_s_05",
            triggerCategory = "STRESSED",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Write down the single next task you need to do, and ignore everything else on your list for 15 minutes.",
            rationale = "Radical task reduction eliminates cognitive overwhelm and executive dysfunction paralysis."
        ),

        // === HOPELESS ===
        CopingCard(
            id = "c_hp_01",
            triggerCategory = "HOPELESS",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Remind yourself: 'I only have to stay clear for the next 15 minutes.' Set a 15-minute timer.",
            rationale = "Time horizon contraction prevents the brain from being overwhelmed by the weight of forever."
        ),
        CopingCard(
            id = "c_hp_02",
            triggerCategory = "HOPELESS",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Look back at your cumulative days clear. That progress is permanent and cannot be erased.",
            rationale = "Objective visual evidence of past success refutes catastrophic all-or-nothing cognitive distortions."
        ),
        CopingCard(
            id = "c_hp_03",
            triggerCategory = "HOPELESS",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Place your hand over your heart, feel your heartbeat, and repeat: 'I am here. I am safe. This will pass.'",
            rationale = "Self-compassion touch increases heart rate variability and activates neurobiological resilience."
        ),
        CopingCard(
            id = "c_hp_04",
            triggerCategory = "HOPELESS",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Call or text 988 or SAMHSA 1-800-662-4357 right now. You are worthy of support.",
            rationale = "Professional crisis counselors provide non-judgmental presence to carry you through deep despair."
        ),

        // === GENERAL ===
        CopingCard(
            id = "c_g_01",
            triggerCategory = "GENERAL",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Urge Surfing: Picture the craving as an ocean wave. It rises, peaks, and naturally breaks within 15 minutes.",
            rationale = "Urges are neurochemical surges that naturally decay when observed with curiosity rather than struggle."
        ),
        CopingCard(
            id = "c_g_02",
            triggerCategory = "GENERAL",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Change your physical posture: Stand tall, stretch your arms overhead, and look up at the sky or ceiling.",
            rationale = "Postural expansion alters endocrine feedback and breaks habitual physical triggers associated with urges."
        ),
        CopingCard(
            id = "c_g_03",
            triggerCategory = "GENERAL",
            minUrgeLevel = UrgeLevel.WHITE_KNUCKLING,
            actionText = "Listen to an uplifting song with headphones at a comfortable volume and tap your foot to the beat.",
            rationale = "Auditory entrainment stimulates dopamine release through safe, healthy pathways."
        ),
        CopingCard(
            id = "c_g_04",
            triggerCategory = "GENERAL",
            minUrgeLevel = UrgeLevel.CRITICAL,
            actionText = "Get up and move to a different room right now. Do not stay in the spot where the urge hit you.",
            rationale = "Physical environmental transitions disrupt conditioned behavioral cue responses."
        ),
        CopingCard(
            id = "c_g_05",
            triggerCategory = "GENERAL",
            minUrgeLevel = UrgeLevel.PASSING,
            actionText = "Count backward from 100 by 7s (100, 93, 86, 79...).",
            rationale = "Complex working memory tasks force blood flow into the prefrontal cortex, deactivating the craving loop."
        )
    )
}
